const CREATE_ORDER_WATCHER = 'coinshift/auth/CREATE_ORDER_WATCHER'
const FETCH_ORDER_WATCHER = 'coinshift/auth/FETCH_ORDER_WATCHER'
const POPULATE_ORDER = 'coinshift/auth/POPULATE_ORDER'
const UPDATE_ORDER_ERROR = 'coinshift/auth/UPDATE_ORDER_ERROR'

export {
  CREATE_ORDER_WATCHER,
  FETCH_ORDER_WATCHER,
  POPULATE_ORDER,
  UPDATE_ORDER_ERROR,
}
