const FETCH_METHODS_WATCHER = 'coinshift/transfer/FETCH_METHODS_WATCHER'
const FETCH_RATE_WATCHER = 'coinshift/transfer/FETCH_RATE_WATCHER'
const POPULATE_SETTLE_METHODS = 'coinshift/transfer/POPULATE_SETTLE_METHODS'
const POPULATE_DEPOSIT_METHODS = 'coinshift/transfer/POPULATE_DEPOSIT_METHODS'
const SELECT_SETTLE_METHOD = 'coinshift/transfer/SELECT_SETTLE_METHOD'
const SELECT_DEPOSIT_METHOD = 'coinshift/transfer/SELECT_DEPOSIT_METHOD'
const POPULATE_RATE = 'coinshift/transfer/POPULATE_RATE'
const POPULATE_SETTLE_ADDRESS = 'coinshift/transfer/POPULATE_SETTLE_ADDRESS'
const POPULATE_RECENT_DEPOSITS = 'coinshift/transfer/POPULATE_RECENT_DEPOSITS'
const FETCH_RECENT_DEPOSITS_WATCHER = 'coinshift/transfer/FETCH_RECENT_DEPOSITS_WATCHER'
const FETCH_STATS_WATCHER = 'coinshift/transfer/FETCH_STATS_WATCHER'
const POPULATE_STATS = 'coinshift/transfer/POPULATE_STATS'


export {
  FETCH_RATE_WATCHER,
  FETCH_METHODS_WATCHER,
  POPULATE_SETTLE_METHODS,
  POPULATE_DEPOSIT_METHODS,
  SELECT_SETTLE_METHOD,
  SELECT_DEPOSIT_METHOD,
  POPULATE_SETTLE_ADDRESS,
  POPULATE_RATE,
  POPULATE_RECENT_DEPOSITS,
  FETCH_RECENT_DEPOSITS_WATCHER,
  FETCH_STATS_WATCHER,
  POPULATE_STATS
}
