const UPDATE_IS_LOADING = 'coinshift/common/UPDATE_IS_LOADING'
const UPDATE_FETCH_RATE_STATUS = 'coinshift/common/UPDATE_FETCH_RATE_STATUS'
const UPDATE_ORDER_STATUS = 'coinshift/common/UPDATE_ORDER_STATUS'

export { UPDATE_IS_LOADING, UPDATE_FETCH_RATE_STATUS, UPDATE_ORDER_STATUS}
